/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminReservasRouteImport } from './routes/admin.reservas'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminReservasIndexRouteImport } from './routes/admin.reservas.index'
import { Route as AdminReservasIdRouteImport } from './routes/admin.reservas.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReservasRoute = AdminReservasRouteImport.update({
  id: '/admin/reservas',
  path: '/admin/reservas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReservasIndexRoute = AdminReservasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminReservasRoute,
} as any)
const AdminReservasIdRoute = AdminReservasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminReservasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reservas': typeof AdminReservasRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/reservas/$id': typeof AdminReservasIdRoute
  '/admin/reservas/': typeof AdminReservasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin': typeof AdminIndexRoute
  '/admin/reservas/$id': typeof AdminReservasIdRoute
  '/admin/reservas': typeof AdminReservasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reservas': typeof AdminReservasRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/reservas/$id': typeof AdminReservasIdRoute
  '/admin/reservas/': typeof AdminReservasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin/login'
    | '/admin/reservas'
    | '/admin/'
    | '/admin/reservas/$id'
    | '/admin/reservas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/login'
    | '/admin'
    | '/admin/reservas/$id'
    | '/admin/reservas'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/admin/login'
    | '/admin/reservas'
    | '/admin/'
    | '/admin/reservas/$id'
    | '/admin/reservas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminReservasRoute: typeof AdminReservasRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reservas': {
      id: '/admin/reservas'
      path: '/admin/reservas'
      fullPath: '/admin/reservas'
      preLoaderRoute: typeof AdminReservasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reservas/': {
      id: '/admin/reservas/'
      path: '/'
      fullPath: '/admin/reservas/'
      preLoaderRoute: typeof AdminReservasIndexRouteImport
      parentRoute: typeof AdminReservasRoute
    }
    '/admin/reservas/$id': {
      id: '/admin/reservas/$id'
      path: '/$id'
      fullPath: '/admin/reservas/$id'
      preLoaderRoute: typeof AdminReservasIdRouteImport
      parentRoute: typeof AdminReservasRoute
    }
  }
}

interface AdminReservasRouteChildren {
  AdminReservasIdRoute: typeof AdminReservasIdRoute
  AdminReservasIndexRoute: typeof AdminReservasIndexRoute
}

const AdminReservasRouteChildren: AdminReservasRouteChildren = {
  AdminReservasIdRoute: AdminReservasIdRoute,
  AdminReservasIndexRoute: AdminReservasIndexRoute,
}

const AdminReservasRouteWithChildren = AdminReservasRoute._addFileChildren(
  AdminReservasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminReservasRoute: AdminReservasRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
